#!/usr/bin/env awk -f
/[0-9].*/ {
    if ($NF == "*") {
        r += x
        x = 1
        operator = "*"
    }
    else if ($NF == "+") {
        r += x
        x = 0
        operator = "+"
    }
    if (operator == "*") {
        x *= $1
    } else if (operator == "+") {
        x += $1
    }
}
END { r += x; print r }
