#!/usr/bin/env awk -f
/[0-9].*/ {
    if ($NF == "*") {
        r += x
        print "-----"
        print r
        print $NF
        x = 1
        operator = "*"
    }
    else if ($NF == "+") {
        r += x
        print "-----"
        print r
        print $NF
        x = 0
        operator = "+"
    }
    if (operator == "*") {
        x *= $1
    } else if (operator == "+") {
        x += $1
    }
    print $1, x
}
END { r += x; print "RESULT:", r }
