#!/usr/bin/env awk -f
BEGIN { FS ="" }
{ 
    for (i=1; i<=NF; i++)  {
        a[NR,i] = $i
    }
}
NF>p { p = NF }
END {    
    for(j=1; j<=p; j++) {
        str=a[1,j]
        for(i=2; i<=NR; i++){
            if (a[i,j] == "*" || a[i,j] == "+") {
                str=str" "a[i,j];
            }
            else {
                str=str""a[i,j];
            }
        }
        print str
    }
}
