#!/usr/bin/env awk -f
BEGIN { FS = "" }
NR == 1 { 
    for (i = 1; i <= NF; i++) {
        if ($i == "S") {
            b[i]= 1
        }
    }
}
NR > 1 {
    for (i = 1; i <= NF; i++) {
        if ($i == "^" && b[i]) {
            b[i-1] += b[i]
            b[i+1] += b[i]
            b[i] = 0
            r += 1
        }
    }
}
END { 
    r2 = b[1] - 1
    for (i = 1; i <= NF; i++) {
        r2 += b[i]
    }
    print r 
    print r2
}
