#!/usr/bin/env awk -f
BEGIN { FS = "" }
NR==1 { 
    printf("%s ", NR)
    for (i = 1; i <= NF; i++) {
        if ($i == "S") {
            b[NR, i]= 1
        } else {
            b[NR, i]= 0
        }
        printf("%i", b[NR, i])
    }
    printf("\n")
}
NR>1 {
    printf("%s ", NR)
    for (i = 1; i <= NF; i++) {
        if (!b[NR, i]) {
            b[NR, i]= b[NR-1, i]
        }
        if ($i == "^" && b[NR-1, i]) {
            b[NR, i-1]= 1
            b[NR, i+1]= 1
            b[NR, i]= 0
            r += 1
        }
    }
    for (i = 1; i <= NF; i++) {
        printf("%i", b[NR, i])
    }
    printf("\n")
}
END { print r }
