#!/usr/bin/env gawk -f

function dist(x1, y1, z1, x2, y2, z2) {
    return (x1 - x2)**2 + (y1 - y2)**2 + (z1 - z2)**2
}

BEGIN { FS="," }
{
    x[NR] = $1
    y[NR] = $2
    z[NR] = $3
}
END {
    for (i = 1; i < NR; i++) {
        for (j = i + 1; j <=NR; j++) {
            d = dist(x[i], y[i], z[i], x[j], y[j], z[j])
            distances[d][1] = i
            distances[d][2] = j
        }
    }

    for (i = 1; i <= 1000; i++) {
        print i
        min_d = 1e9
        for (d in distances) {
            if (int(d) < min_d) {
                min_d = int(d)
            }
        }
        
        a = distances[min_d][1]
        b = distances[min_d][2]

        saved[i][a] = ""
        saved[i][b] = ""

        for (j in saved) {
            for (k in saved) {
                if (j == k || !j || !k) {
                    continue
                }
                if (a in saved[j] && a in saved[k]) {
                    for (c in saved[k]) { 
                        saved[j][c] = ""
                    }
                    delete saved[k]
                }
                else if (b in saved[j] && b in saved[k]) {
                    for (c in saved[k]) { 
                        saved[j][c] = ""
                    }
                    delete saved[k]
                }
            }
        }
        delete distances[min_d]
    }
    r = 1
    for (i = 1; i <= 3; i++) {
        max_size = 0
        for (idx in saved) {
            size = length(saved[idx])
            if (size > max_size) {
                max_idx = idx
                max_size = size
            }
        }
        print max_size
        r *= max_size
        delete saved[max_idx]
    }
    print "RESULT:", r
}

